site_name: Scar Language Documentation
site_url: https://scar-lang.org
repo_url: https://github.com/navid-m/scar

nav:
   - Home: index.md
   - Core Constructs:
        - Primitive Data Types: datatypes.md
        - Variables: variables.md
        - Control Flow: controlflow.md
        - Functions: functions.md
        - Classes: classes.md
        - Comments: comments.md
        - Access Modifiers: accessmods.md
   - Parallelism:
        - Parallel block: parallelblock.md
        - Parallel for: parallelfor.md
        - Parallel while: parallelwhile.md
        - Reduce clause: reduce.md
   - Memory Management:
        - Allocation on Heap: heap.md
        - Allocation on Stack: stack.md
        - Optional Garbage Collection: garbagecollection.md
   - Standard Library:
        - Collections: stdlib/collections.md
        - Strings: stdlib/strings.md
        - Math: stdlib/math.md
        - I/O: stdlib/io.md
        - Crypto: stdlib/crypto.md
        - Hash: stdlib/hash.md
        - Regex: stdlib/regex.md
        - Log: stdlib/log.md
        - Concurrency: stdlib/concurrency.md
        - Random: stdlib/random.md
        - Time: stdlib/time.md
        - JSON: stdlib/json.md
        - FS: stdlib/filesystem.md
        - OS: stdlib/os.md
   - Toolchain:
        - Compiler: compiler.md
        - Interpreter: interpreter.md
        - Debugger: debugger.md
        - Package Manager: package-manager.md
   - About:
        - Philosophy and Justification: philosophy.md
        - License: license.md
theme:
   name: material
   logo: img/icon.png
   palette:
      primary: black
      accent: blue
      scheme: slate
