site_name: Scar Language Documentation
site_url: https://scar-lang.org
repo_url: https://github.com/navid-m/scar

nav:
   - Home: index.md
   - Core Constructs:
        - Primitive Data Types: datatypes.md
        - Variables: variables.md
        - Control Flow: controlflow.md
        - Functions: functions.md
        - Classes: classes.md
        - Comments: comments.md
        - Access Modifiers: accessmods.md
   - Parallelism:
        - Parallel block: parallelblock.md
        - Parallel for: parallelfor.md
        - Parallel while: parallelwhile.md
        - Reduce clause: reduce.md
   - Memory Management:
        - Allocation on Heap: heap.md
        - Allocation on Stack: stack.md
        - Optional Garbage Collection: garbagecollection.md
   - Standard Library:
        - collections: stdlib/collections.md
        - strings: stdlib/strings.md
        - math: stdlib/math.md
        - io: stdlib/io.md
        - csv: stdlib/csv.md
        - path: stdlib/path.md
        - crypto: stdlib/crypto.md
        - net: stdlib/net.md
        - errors: stdlib/errors.md
        - hash: stdlib/hash.md
        - regex: stdlib/regex.md
        - log: stdlib/log.md
        - threads: stdlib/threads.md
        - runtime: stdlib/runtime.md
        - random: stdlib/random.md
        - time: stdlib/time.md
        - typecons: stdlib/typecons.md
        - json: stdlib/json.md
        - fs: stdlib/fs.md
        - os: stdlib/os.md
        - sort: stdlib/sort.md
        - uri: stdlib/uri.md
   - Toolchain:
        - Compiler: compiler.md
        - Interpreter: interpreter.md
        - Debugger: debugger.md
        - Package Manager: package-manager.md
   - About:
        - Philosophy and Justification: philosophy.md
        - License: license.md
theme:
   name: material
   logo: img/icon.png
   palette:
      primary: black
      accent: blue
      scheme: slate
